version: "2"

services:
  cassandra-one:
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - cassandra/env_one
    build:
      context: ./cassandra
    networks:
      partition-one:
        ipv4_address: 192.168.15.15
    depends_on:
      - router

  cassandra-two:
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - cassandra/env_two
    build:
      context: ./cassandra
    networks:
      partition-two:
        ipv4_address: 192.168.16.16
    depends_on:
      - router

  router:
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      partition-one:
        ipv4_address: 192.168.15.2
      partition-two:
        ipv4_address: 192.168.16.2
    build:
      context: ./router


networks:
  partition-one:
    ipam:
      config:
        - subnet: 192.168.15.0/24
  partition-two:
    ipam:
      config:
        - subnet: 192.168.16.0/24